# Generated by Django 3.1.2 on 2020-11-01 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0002_auto_20201101_1110'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
