# Generated by Django 3.1.2 on 2020-11-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0003_auto_20201101_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
