# Generated by Django 3.1.2 on 2020-11-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
