# Generated by Django 3.1.2 on 2020-10-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
