# Generated by Django 3.1.2 on 2020-10-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_banner_banner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_name',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
