# Generated by Django 3.1.2 on 2020-11-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
